### PR TITLE
Update the package description in ghc-prof-flamegraph.cabal

### PR DESCRIPTION
**Pull request by UnkindPartition**
@bitonic how does this look?

### CODE REVIEW

**Comment by UnkindPartition** [comment]
BTW, I tried to get the markup right, but I don't know a way to preview it, so you might want to upload this as a package candidate first.

**Comment by bitonic** [comment]
Tested on hackage, looks good. Thanks!

**Comment by bitonic** [comment]
@UnkindPartition I've tested the release candidate and it looks good, but I realized I don't have permissions for this repo anymore!

Maybe @mgsloan / @snoyberg can merge?

**Comment by snoyberg** [comment]
Merged, thanks @UnkindPartition! And @bitonic, I've invited you back as a writer on this repo.

**Comment by bitonic** [comment]
I've uploaded the new package as version 0.2.0.1.

**Pull request merged**
